# vim: set ft=yaml ts=2 expandtab:
---

namespace: mafalb
name: copr
version: 0.1.1
readme: README.md

authors:
- Markus Falb <markus.falb@mafalb.at>

description: Ansible collection for copr plugin

license:
- GPL-3.0-or-later

tags:
- yum
- dnf
- copr

dependencies: {}

repository: https://github.com/mafalb/ansible-collection-copr
documentation: https://github.com/mafalb/ansible-collection-copr
homepage: https://github.com/mafalb/ansible-collection-copr
issues: https://github.com/mafalb/ansible-collection-copr/issues

...
