# vim: set ft=yaml ts=2 expandtab:
---

- name: Converge
  hosts: all
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
  roles:

  # on non RHELish systems
  #
  - role: mafalb.copr.plugin
    when:
    - ansible_os_family != 'RedHat'

  # on non RHELish systems it should not fail
  #
  - role: mafalb.copr.repo
    repo: copart/restic
    when:
    - ansible_os_family != 'RedHat'

  # on non RHELish systems it should not fail
  #
  - role: mafalb.copr.repo
    repo: copart/restic
    when:
    - ansible_os_family != 'RedHat'
  

  # skip on EL 6
  #
  - role: mafalb.copr.plugin
    when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution != 'Fedora'
    - ansible_distribution_major_version is version('7', '>=')

  # skip on Fedora, i.e. only on RHEL and clones
  #
  - role: mafalb.copr.repo
    repo: copart/restic
    when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution != 'Fedora'
    - ansible_distribution_major_version is version('7', '>=')


  # install plugin on Fedora
  #
  - role: mafalb.copr.plugin
    when:
    - ansible_distribution == 'Fedora'

  # only on Fedora
  - role: mafalb.copr.repo
    repo: eklitzke/watchman
    when: ansible_distribution == 'Fedora'

...
