# vim: set ft=yaml ts=2 expandtab:
---

- name: Converge proxy
  hosts: t_proxy
  roles:
  - role: mafalb.squid.server

- name: Converge
  hosts: all,!t_proxy

  tasks:

  - name: group by EL and clones
    group_by:
      key: EL{{ ansible_distribution_major_version }}
      parents:
      - EL
    when:
    - false
    - ansible_os_family == 'RedHat'
    - ansible_distribution != 'Fedora'
    # make molecules idempotence happy
    #
    changed_when: false

  - name: group by Fedora and clones
    group_by:
      key: Fedora{{ ansible_distribution_major_version }}
      parents:
      - Fedora
    when:
    - false
    - ansible_distribution == 'Fedora'
    # make molecules idempotence happy
    #
    changed_when: false


- name: Converge EL6
  hosts: t_centos6,EL6,!t_proxy

  environment:
    http_proxy: http://t_proxy:3128
    https_proxy: http://t_proxy:3128

  roles:

  - role: mafalb.copr.repo
    repo: copart/restic
    copr_repo_uri: https://copr.fedorainfracloud.org/coprs/copart/restic/repo/epel-6/copart-restic-epel-6.repo


- name: Converge EL
  hosts: t_centos7,t_centos8,EL,!EL6,!t_proxy

  environment:
    http_proxy: http://t_proxy:3128
    https_proxy: http://t_proxy:3128

  roles:

  - role: mafalb.copr.repo
    repo: copart/restic


# There is no copart/restic for Fedora, so I install another repo
#
- name: Converge
  hosts: t_fedora31,t_fedora32,t_fedora33,Fedora,!t_proxy

  environment:
    http_proxy: http://t_proxy:3128
    https_proxy: http://t_proxy:3128

  roles:

  - role: mafalb.copr.repo
    repo: eklitzke/watchman

...
