# vim: set ft=yaml ts=2 expandtab:
---

- name: Converge
  hosts: all
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
  roles:
  - role: mafalb.copr.plugin

  # skip on Fedora, i.e. only on RHEL and clones
  #
  - role: mafalb.copr.repo
    repo: copart/restic
    when: ansible_distribution != 'Fedora'

  # only on Fedora
  - role: mafalb.copr.repo
    repo: eklitzke/watchman
    when: ansible_distribution == 'Fedora'

...
