# vim: set ft=yaml ts=2 expandtab:
---

- name: Converge
  hosts: all
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
  roles:
  - role: mafalb.copr.plugin
  - role: mafalb.copr.repo
    repo: copart/restic
    when: ansible_distribution != 'Fedora'

...
