# vim: set ft=yaml ts=2 expandtab:
---

dependency:
  name: galaxy

driver:
  name: docker

# https://github.com/ansible/ansible-lint/issues/731
# revert when fixed
#
lint: |
  set -e
  yamllint .
  #ansible-lint -v
  ansible-lint -v roles/* molecule/default/converge.yml molecule/default/verify.yml molecule/install_molecule.yml molecule/requirements.yml
  flake8 -v

platforms:

  - name: t_${CI_CONTAINER_IMAGE:-centos}${CI_CONTAINER_TAG:-7}
    image: ${CI_CONTAINER_IMAGE:-centos}:${CI_CONTAINER_TAG:-7}

provisioner:
  name: ansible
  ansible_args:
    - --tags=all,debug
    - --diff
  config_options:
    defaults:
      gathering: smart
  lint:
    name: ansible-lint
  env:
    ANSIBLE_COLLECTIONS_PATHS: "../../../../..:~/.ansible/collections"

verifier:
  name: ansible
  lint:
    name: ansible-lint

...
