# vim: set ft=yaml ts=2 expandtab:
---

dependency:
  name: galaxy
  options:
    role-file: idontexist.yml   # avoid warning while running molecule 
    requirements-file: molecule/default/requirements.yml

driver:
  name: docker

# https://github.com/ansible/ansible-lint/issues/731
# revert when fixed
#
lint: |
  set -e
  PATH=${PATH}
  ! grep -r "no_log: false" .
  yamllint .
  ansible-lint -v
  ansible-lint -v roles/*/vars/*.yml
  flake8 -v

platforms:

- name: ${CI_HOSTNAME-"ci-rocky8"}
  image: ${CI_IMAGE:-"quay.io/rockylinux/rockylinux:8"}
  network_type: bridge
  docker_networks:
  - name: molecule-internal
    internal: true
  networks:
  - name: molecule-internal

- name: ci-proxy
  image: quay.io/centos/centos:8
  command: /lib/systemd/systemd
  dockerfile: Dockerfile-systemd.j2
  network_type: bridge
  docker_networks:
  - name: molecule-internal
    internal: true
  networks:
  - name: molecule-external
  - name: molecule-internal
  volumes:
  - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  tmpfs:
  - /run
  - /tmp
  capabilities:
  - SYS_ADMIN
  privileged: ${CI_CONTAINER_PRIVILEGED:-false}
  pre_build_image: ${CI_CONTAINER_PREBUILT:-false}

provisioner:
  name: ansible
  ansible_args:
    - --tags=all,debug
    - --diff
  config_options:
    defaults:
      gathering: smart
  lint:
    name: ansible-lint

verifier:
  name: ansible
  lint:
    name: ansible-lint

...
