# vim: set ft=yaml ts=2 expandtab:
---

- name: Verify
  hosts: all
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"

  tasks:
  - debug: var=ansible_pkg_mgr

  - name: verify that copr plugin is installed
    command: "{{ ansible_pkg_mgr }} copr list mafalb"
    args:
      warn: false
    changed_when: false

...
