# vim: set ft=yaml ts=2 expandtab:
---

- name: Verify
  hosts: all

  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"

  tasks:
  - debug: var=ansible_pkg_mgr

  - name: verify that copr plugin is installed
    shell: |
      set -o pipefail
      {{ ansible_pkg_mgr }} copr list | grep copart/restic
    args:
      warn: false
      executable: /bin/bash
    changed_when: false
    when: ansible_distribution != 'Fedora'

  - name: verify that eklitzke/watchman is installed
    shell: |
      set -o pipefail
      {{ ansible_pkg_mgr }} copr list | grep eklitzke/watchman
    args:
      warn: false
      executable: /bin/bash
    changed_when: false
    when: ansible_distribution == 'Fedora'

...
