# vim: set ft=yaml ts=2 expandtab:
---

- name: Verify
  hosts: all

  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"

  tasks:
  - debug: var=ansible_pkg_mgr

  - name: verify that copart/restic is installed
    command: ls -1 /etc/yum.repos.d/_copr_copart-restic.repo
    changed_when: false
    when: ansible_distribution != 'Fedora'

  - name: verify that eklitzke/watchman is installed
    command: ls /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:eklitzke:watchman.repo
    changed_when: false
    when: ansible_distribution == 'Fedora'

...
