# vim: set ft=yaml ts=2 expandtab:
---

- name: Verify
  hosts: all

  vars:
    restic_repo:
      '6': '_copr_copart-restic.repo'
      '7': '_copr_copart-restic.repo'
      default: '_copr:copr.fedorainfracloud.org:copart:restic.repo'

  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"

  tasks:

  - name: verify that copart/restic is installed
    command: ls -1 /etc/yum.repos.d/{{ restic_repo[ansible_distribution_major_version]|default(restic_repo['default']) }}
    changed_when: false
    when:
    - ansible_distribution != 'Fedora'
    - ansible_distribution_major_version is version('7', '>=')


  - name: verify that eklitzke/watchman is installed
    command: ls /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:eklitzke:watchman.repo
    changed_when: false
    when: ansible_distribution == 'Fedora'

...
