# vim: set ft=yaml ts=2 expandtab:
---

dependency:
  name: galaxy
  options:
    role-file: idontexist.yml   # avoid warning while running molecule 
    requirements-file: molecule/podman/requirements.yml

driver:
  name: podman

# https://github.com/ansible/ansible-lint/issues/731
# revert when fixed
#
lint: |
  set -e
  ! grep -r "no_log: false" .
  yamllint .
  #ansible-lint -v
  ansible-lint -v roles/* molecule/default/converge.yml molecule/default/verify.yml molecule/install_molecule.yml molecule/requirements.yml
  flake8 -v

platforms:

- name: t_${CI_CONTAINER_IMAGE:-centos}${CI_CONTAINER_TAG:-7}
  image: ${CI_CONTAINER_IMAGE:-centos}:${CI_CONTAINER_TAG:-7}
  networks:
  - name: molecule-internal

- name: t_proxy
  image: centos:8
  command: /lib/systemd/systemd
  dockerfile: Dockerfile-systemd.j2
  networks:
  - name: molecule-external
  - name: molecule-internal
  security_opts:
  - seccomp=unconfined
  volumes:
  - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  tmpfs:
  - /run
  - /tmp
  capabilities:
  - SYS_ADMIN
  privileged: true
  #privileged: ${CI_CONTAINER_PRIVILEGED:-false}
  pre_build_image: ${CI_CONTAINER_PREBUILT:-false}

provisioner:
  name: ansible
  ansible_args:
    - --tags=all,debug
    - --diff
  config_options:
    defaults:
      gathering: smart
  lint:
    name: ansible-lint
  env:
    ANSIBLE_COLLECTIONS_PATHS: "../../../../..:~/.ansible/collections"

verifier:
  name: ansible
  lint:
    name: ansible-lint

...
