# vim: set ft=yaml ts=2 expandtab:
---

# either use the installed copr plugin to download
# or
# download it directly
#
# TODO: should be a custom module
#
- block:

  - name: copr repo is enabled (with copr plugin)
    command: "{{ ansible_pkg_mgr }} -y copr remove {{ repo|mandatory }}"
    args:
      removes: /etc/yum.repos.d/{{ repofile }}
    when: copr_repo_uri is not defined

  - name: copr repo is absent (without copr plugin)
    file:
      path: /etc/yum.repos.d/{{ repofile }}
      state: absent
    when: copr_repo_uri is defined

...
