# vim: set ft=yaml ts=2 expandtab:
---

- name: assertions
  assert:
    that:
    - repo is defined
    - (repo|mandatory).split('/')|length == 2
    - ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf'

- name: copr_repo_uri is defined
  assert:
    that:
    - copr_repo_uri is defined
  when:
  - ansible_os_family == 'RedHat'
  - ansible_distribution_major_version is version('6', '<=')

- name: get OS specific variables
  with_first_found:
  - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  - "{{ ansible_os_family }}.yml"
  - noplugin.yml
  include_vars:
    file: "{{ item }}"

- name: include tasks
  include_tasks: "{{ copr_repo_state }}.yml"

...
