# vim: set ft=yaml ts=2 expandtab:
---

name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '40 12 * * 6'

jobs:
  CI:

    runs-on: ubuntu-20.04

    strategy:

      fail-fast: false

      matrix:

        target:
        - centos6
        - centos7
        - centos8
        - fedora31
        - fedora32

        ansible_version:
        - '2.10'
        - '2.9'

        include:

        - target: centos6
          image: centos
          tag: 6

        - target: centos7
          image: centos
          tag: 7

        - target: centos8
          image: centos
          tag: 8

        - target: fedora31
          image: fedora
          tag: 31

        - target: fedora32
          image: fedora
          tag: 32

    env:
      CI_CONTAINER_IMAGE: ${{ matrix.image }}
      CI_CONTAINER_TAG: ${{ matrix.tag }}
      CI_CONTAINER_PRIVILEGED: true
      ANSIBLE_VERSION: ${{ matrix.ansible_version }}

    defaults:
      run:
        working-directory: ansible_collections/mafalb/copr

    steps:

      - name: checkout collection
        uses: actions/checkout@v2
        with:
          path: ansible_collections/mafalb/copr

      - name: install dependencies
        run: ansible-galaxy collection install -r molecule/requirements.yml

      - name: update apt cache
        run: sudo apt-get update

      - name: install molecule
        run: ansible-playbook -D molecule/install_molecule.yml -e molecule_ansible_version=$ANSIBLE_VERSION -t all,debug

      - name: run molecule tests
        run: |
          source ~/.virtualenvs/molecule/bin/activate
          PY_COLORS=1 CI_CONTAINER_IMAGE=$CI_CONTAINER_IMAGE CI_CONTAINER_TAG=$CI_CONTAINER_TAG molecule test

...
