# vim: set ft=yaml ts=2 expandtab:
---

name: CI

on:  # yamllint disable-line rule:truthy

  push:
    branches:
    - '**'
    tags-ignore:
    - '*'

  schedule:
    - cron: '40 12 * * 6'

jobs:
  CI:

    runs-on: ubuntu-20.04

    strategy:

      fail-fast: false

      matrix:

        target:
        - fedora33
        - fedora34
        - c8s
        - alma8
        - rocky8
        - centos7

        ansible_version:
        - '2.9'
        - '2.10'
        - '2.11'

    env:

      ANSIBLE_VERSION: ${{ matrix.ansible_version }}
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1


    defaults:
      run:
        working-directory: ansible_collections/mafalb/copr

    steps:

      - name: checkout collection
        uses: actions/checkout@v2
        with:
          path: ansible_collections/mafalb/copr

      - name: install mafalb.ansible
        run: ansible-galaxy collection install mafalb.ansible

      # note: this uses ansible-playbook from system ansible
      #
      - name: install molecule
        run: |
          sudo apt install ansible
          /usr/bin/ansible-playbook -D ~/.ansible/collections/ansible_collections/mafalb/ansible/playbooks/molecule.yml -e molecule_ansible_version=$ANSIBLE_VERSION -t all,debug

      - name: check ansible version
        run: |
          source ~/.virtualenvs/molecule/bin/activate
          ansible --version | grep "^ansible.* ${{ matrix.ansible_version }}"

      - name: run molecule tests
        run: |
          source ~/.virtualenvs/molecule/bin/activate
          molecule test -e .env-${{ matrix.target }}.yml --destroy never

      - name: run molecule tests
        run: |
          source ~/.virtualenvs/molecule/bin/activate
          molecule test -e .env-${{ matrix.target }}.yml -s remove


...
